### ISSUE TITLE
[BUG] Version mismatch error

### ISSUE THREAD

**Issue by ruudboon** [FriendsOfPHP/pickle#165] opened 2020-01-28 08:36 UTC
When for example installing Swoole you get the following error:

Version mismatch - 'SWOOLE_VERSION' != '4.4.15' in source vs. XML  
Swoole uses `#define PHP_SWOOLE_VERSION SWOOLE_VERSION` probably causing the issue. 

Something similar occurs with Xdebug
Couldn't parse the version defined in the PHP_XDEBUG_VERSION macro
I assume that PHP_(package)_VERSION is replaced with (package)_VERSION

**Comment by Hywan** [comment] 2020-01-29 07:14
Can you give me the command lines you run please?

**Comment by ruudboon** [comment] 2020-01-29 07:17
```
sudo bin/pickle install swoole
```

**Comment by pierrejoye** [comment] 2020-05-24 12:45
This should be fixed now, we look for this constant in all files recursively.

**Comment by elovin** [comment] 2020-07-01 20:31
When I run `sudo ./pickle.phar install xdebug`
I also get this error:

``` - Installing xdebug (latest-stable): Downloading (100%)         

In Version.php line 91:
                                                                              
  Couldn't parse or find the version defined in the PHP_XDEBUG_VERSION macro
```

**Comment by vstokarev** [comment] 2020-07-09 23:31
I cannot install xdebug too, same error, latest version (0.6.0), please reopen this issue.

**Comment by pierrejoye** [comment] 2020-07-11 16:08
Ok, will try to take a look at it soon.

In the meantime, which command call did you use to install xdebug?

**Comment by vstokarev** [comment] 2020-07-11 17:37
I used `pickle install xdebug`

The problem is that xdebug does not have PHP_ prefix in version macro:
https://github.com/xdebug/xdebug/blob/master/php_xdebug.h#L23

It can be fixed by updating regexp which is used for searching versions in `src/Package/Util/Header/Version.php`. I updated it locally, made a new build and it worked just fine. I can submit a pull request later today.

**Comment by vstokarev** [comment] 2020-07-11 17:52
PR: https://github.com/FriendsOfPHP/pickle/pull/185

**Comment by faizanakram99** [comment] 2020-08-30 00:20
![image](https://user-images.githubusercontent.com/10880992/91648391-ae5af280-ea84-11ea-92f3-3e7e0e728b76.png)

Same issue with sqlsrv or pdo_sqlsrv extensions

**Comment by vstokarev** [comment] 2020-08-30 04:19
It is probably a different issue @faizanakram99 .

**Comment by faizanakram99** [comment] 2020-08-30 04:59
> It is probably a different issue @faizanakram99 .

Think it's the same as OP reported, the error messages are the same

**Comment by vstokarev** [comment] 2020-08-30 05:19
Yes, you're right. And this is probably a reason for that:
https://github.com/microsoft/msphpsql/blob/master/source/shared/version.h#L64

Not sure how it can be fixed in pickle though.

**Comment by pierrejoye** [comment] 2020-08-30 11:58
We could fix it but it would be endless fixes then (Been there in the old pear/pecl):

Pickle uses composer. Composer supports semver valid versions only.

What I was thinking is a kind of flags to allow users to install. However ideally upstream developers should use semver only versions.

**Comment by pierrejoye** [comment] 2020-08-30 11:58
As of SqlSrv they should use the macros, it is part of the php extension references. btw :)

**Comment by pierrejoye** [comment] 2020-08-30 11:59
(they removed them as I added them in the early days of this extension)

**Closed** 2020-08-30 12:26 UTC
Labels: bug

**Comment by grikdotnet** [comment] 2020-10-17 12:07
Well, I still get an version error when trying to install xdebug from source in a local folder.

**Comment by faizanakram99** [comment] 2020-10-17 13:51
> As of SqlSrv they should use the macros, it is part of the php extension references. btw :)

Sorry I don't know anything about extension development, is this worth an issue in ext sqlsrv repository ?
If yes, could you help me in opening an issue there ?

**Comment by strarsis** [comment] 2020-10-20 00:45
With latest pickle (`v0.6.0`) the installation of `xdebug` PHP extension fails:
```sh
> pickle install xdebug
pickle install xdebug
  - Installing xdebug (latest-stable): Downloading (100%)

In Version.php line 91:

  Couldn't parse or find the version defined in the PHP_XDEBUG_VERSION macro
````

**Comment by duncan3dc** [comment] 2020-10-26 13:39
I think the issue with sqlsrv is that they are building the constant dynamically, which Pickle doesn't support:
https://github.com/microsoft/msphpsql/issues/1210

**Comment by mleczakm** [comment] 2020-11-09 21:31
I'm still unable to install latest swoole using pickle.

**Comment by TheHett** [comment] 2020-11-27 15:00
How I understand this PR isn't included in latest release.
When is the next release?

**Comment by TheHett** [comment] 2020-11-27 15:02
Still not working :(

```
RUN set -ex \
	&& apk add \
		    libzip-dev \
	&& docker-php-ext-install -j$(nproc) zip \
	&& curl -L -o /usr/local/bin/pickle https://github.com/FriendsOfPHP/pickle/releases/latest/download/pickle.phar \
	&& chmod +x /usr/local/bin/pickle

RUN pickle install xdebug \
    && docker-php-ext-enable xdebug
```

**Comment by pierrejoye** [comment] 2020-11-28 17:00
I will do a release this week.

For this, you will need to use current git

**Comment by faizanakram99** [comment] 2020-12-03 02:35
msphpsql changed version number upstream but unfortunately it still doesn't work, tried with master branch too

https://github.com/microsoft/msphpsql/issues/1210#issuecomment-737413033

**Comment by TheHett** [comment] 2020-12-09 10:59
@pierrejoye current git doesn't work on php 8 :(

```
# Pickle
RUN set -ex \
	&& apk add libzip-dev \
	&& docker-php-ext-install -j$(nproc) zip \
	&& git clone https://github.com/FriendsOfPHP/pickle.git /opt/pickle \
	&& cd /opt/pickle && /usr/bin/composer install \
	&& ln -s /opt/pickle/bin/pickle /usr/local/bin/pickle \
	&& chmod +x /usr/local/bin/pickle
```


```
    - Installation request for composer/composer 1.10.6 -> satisfiable by composer/composer[1.10.6].
    - composer/composer 1.10.6 requires php ^5.3.2 || ^7.0 -> your PHP version (8.0.0) does not satisfy that requirement.
```

Can you release?

**Comment by vicalle12** [comment] 2021-01-27 09:17
I still have same problem

**Comment by mlocati** [comment] 2021-01-27 13:24
> I still have same problem

@vicalle12 
1. what's your pickle version (`pickle --version` or `php pickle.phar --version`)?
2. what's the command that fails for you (eg `pickle install ...`)?

**Comment by vicalle12** [comment] 2021-01-27 14:32
> > I still have same problem
> 
> @vicalle12
> 
> 1. what's your pickle version (`pickle --version` or `php pickle.phar --version`)?
> 2. what's the command that fails for you (eg `pickle install ...`)?

Command
`pickle install xdebug`
in Dockerfile: `FROM php:8.0.0RC3-fpm-alpine`
Error: 
`pickle install xdebug
  - Installing xdebug (latest-stable): Downloading (100%)

In Version.php line 91:

  Couldn't parse or find the version defined in the PHP_XDEBUG_VERSION macro`

**Comment by mlocati** [comment] 2021-01-27 14:48
@vicalle12 What's the version of pickle you are using? `pickle --version`

**Comment by Ahmard** [comment] 2022-06-18 08:13
Having same issue too, I simply ran
> pickle install openswoole

![Screenshot from 2022-06-18 09-11-10](https://user-images.githubusercontent.com/44737217/174429092-73e810f6-7e18-48ee-b780-87a1bbc55e80.png)

Using **v0.7.11**

**Comment by nikspyratos** [comment] 2023-08-26 15:31
```
Version mismatch - 'OpenSwoole-' != '22.0.0' in source vs. XML
```
Same thing for me on PHP8.2. Latest pickle.

**Comment by nikspyratos** [comment] 2023-12-12 09:53
Gave this another go, adding `--version-override 22.1.2` made it install. It has some other build issues (on my M1 at least), but what worked was copying a missing pcre2 file to my PHP installation: 

`cp /opt/homebrew/Cellar/pcre2/10.42/include/pcre2.h /opt/homebrew/Cellar/php/8.3.0/include/php/ext/pcre/pcre2.h` (yours may differ in versions)

Then installing with version override worked, if using none of the install options.

Otherwise for dev right now, if you're using Laravel Octane, it may be simpler to use Roadrunner.
